////////////////////////////////////////////////////////////////////////
//
// Altova.h
//
// This file was generated by XMLSpy 2021r2sp1 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//
////////////////////////////////////////////////////////////////////////

#pragma once
#ifndef ALTOVADEFS_H_INCLUDED
#define ALTOVADEFS_H_INCLUDED


#if !defined( __GNUC__ )
#ifdef ALTOVA_EXPORTS
#define ALTOVA_DECLSPECIFIER __declspec(dllexport)
#else
#define ALTOVA_DECLSPECIFIER __declspec(dllimport)
#endif
#else
#define ALTOVA_DECLSPECIFIER
#endif


#endif
