////////////////////////////////////////////////////////////////////////
//
// AltovaXMLAPI.h
//
// This file was generated by XMLSpy 2021r2sp1 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//
////////////////////////////////////////////////////////////////////////

#pragma once
#ifndef ALTOVA_XML_API_H_INCLUDED
#define ALTOVA_XML_API_H_INCLUDED


#if !defined( __GNUC__ )
#ifdef ALTOVAXML_EXPORTS
	#define ALTOVAXML_DECLSPECIFIER __declspec(dllexport)
	#define ALTOVAXML_EXPIMP_TEMPLATE
#else
	#define ALTOVAXML_DECLSPECIFIER __declspec(dllimport)
	#define ALTOVAXML_EXPIMP_TEMPLATE extern
#endif
#else
#define ALTOVAXML_DECLSPECIFIER
#endif

#ifndef _MFC_VER
	#pragma warning(disable: 4660)
	#pragma warning(disable: 4231)
	#pragma warning(disable: 4251)
#endif


#endif // ALTOVA_XML_API_H_INCLUDED
