////////////////////////////////////////////////////////////////////////
//
// StdAfx.h
//
// This file was generated by XMLSpy 2021r2sp1 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//
////////////////////////////////////////////////////////////////////////

#pragma once
#ifndef indoorgmlcore_STDAFX_H_INCLUDED
#define indoorgmlcore_STDAFX_H_INCLUDED

#if !defined( __GNUC__ )

#define VC_EXTRALEAN // Exclude rarely-used stuff from Windows headers
#include <afx.h>
#include <afxwin.h>
#include <afxdisp.h>

#endif





#include "../Altova/Altova.h"
#include "../Altova/SchemaTypes.h"
#include "../Altova/AltovaException.h"
#include "../AltovaXML/XmlException.h"
#include "../AltovaXML/Node.h"
using namespace altova;


//{{AFX_INSERT_LOCATION}}

#endif // indoorgmlcore_STDAFX_H_INCLUDED
