////////////////////////////////////////////////////////////////////////
//
// indoorgmlcoreTest.h
//
// This file was generated by XMLSpy 2021r2sp1 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//
////////////////////////////////////////////////////////////////////////


#ifndef indoorgmlcoreTest_H_INCLUDED
#define indoorgmlcoreTest_H_INCLUDED

#pragma once

#include "Resource.h"

#endif // indoorgmlcoreTest_H_INCLUDED
