////////////////////////////////////////////////////////////////////////
//
// StdAfx.h
//
// This file was generated by XMLSpy 2021r2sp1 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//
////////////////////////////////////////////////////////////////////////

#pragma once
#ifndef indoorgmlcoreTest_STDAFX_H_INCLUDED
#define indoorgmlcoreTest_STDAFX_H_INCLUDED

#if !defined( __GNUC__ )

#define VC_EXTRALEAN		// Exclude rarely-used stuff from Windows headers
#include <afx.h>
#include <afxwin.h>			// MFC core and standard components
#include <afxext.h>			// MFC extensions
#include <afxdtctl.h>		// MFC support for Internet Explorer 4 Common Controls

#ifndef _AFX_NO_AFXCMN_SUPPORT
	#include <afxcmn.h>		// MFC support for Windows Common Controls
#endif // _AFX_NO_AFXCMN_SUPPORT

#endif



#include "../Altova/Altova.h"
#include "../Altova/SchemaTypes.h"
#include "../Altova/AltovaException.h"

#include "../AltovaXML/XmlException.h"
#include "../AltovaXML/Node.h"

using namespace altova;


//{{AFX_INSERT_LOCATION}}

#endif // indoorgmlcoreTest_STDAFX_H_INCLUDED
